job.pool.useVirtualThreads=false
job.pool.coreSize=4
job.pool.maxSize=16
job.pool.keepAliveSeconds=60
job.pool.queueSize=1024

job.task.pool.useVirtualThreads=false
job.task.pool.coreSize=8
job.task.pool.maxSize=64
job.task.pool.keepAliveSeconds=60
job.task.pool.queueSize=1024

cache.doc.guava.spec=maximumSize=1000,expireAfterAccess=20s