{
 "title": "Cache Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_name", "label": "Test Name", "query": { "query": "label_values(test)" } },
   { "name": "interval", "query": "3s" }
  ]
 },
 "panels": [
  {
   "title": "Cache Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cache_guava_document:size{test=\"$test_name\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "cache_guava_document:size_max_spike{test=\"$test_name\"}",
     "legendFormat": "Max Spike"
    },
    {
     "expr": "cache_guava_document:size_avg{test=\"$test_name\"}",
     "legendFormat": "Size Avg"
    },
    {
     "expr": "cache_guava_document:size_avg_running{test=\"$test_name\"}",
     "legendFormat": "Size Avg Running"
    }
   ]
  },
  {
   "title": "Cache Efficiency",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(cache_guava_document:lookups_count{test=\"$test_name\", type=\"hit\"}) / sum(cache_guava_document:lookups_count{test=\"$test_name\"})",
     "legendFormat": "Hit Ratio %"
    }
   ]
  },
  {
   "title": "Miss Load Time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "cache_guava_document:avg_load_time_ns{test=\"$test_name\"}",
     "legendFormat": "Load Time"
    }
   ]
  },
  {
   "title": "Cache Hits",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "cache_guava_document:lookups_count{test=\"$test_name\", type=\"hit\"}",
     "legendFormat": "Hits"
    },
    {
     "expr": "cache_guava_document:lookups_count{test=\"$test_name\", type=\"miss\"}",
     "legendFormat": "Misses"
    }
   ]
  }
 ]
}