{
 "title": "Job Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_name", "label": "Test Name", "query": { "query": "label_values(test)" } },
   { "name": "interval", "query": "3s" },
   { "name": "scheme", "label": "Scheme", "query": { "query": "label_values(scheme)" } }
  ]
 },
 "panels": [
  {
   "title": "Jobs Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "job:count_total{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Frequency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "job:frequency_avg_Hz{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Frequency"
    },
    {
     "expr": "job:frequency_moving_avg_Hz{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Frequency Moving Avg"
    },
    {
     "expr": "irate(job:count_total{test=\"$test_name\", scheme=\"$scheme\"}[$__rate_interval])",
     "legendFormat": "Rate Grafana"
    }
   ]
  },
  {
   "title": "Duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "job:duration_moving_avg_ms{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Duration Moving Avg"
    }
   ]
  },
  {
   "title": "Job Tasks Cache Hit Avg",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "job:uri_cache_hit_avg{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Cache Hit Avg"
    }
   ]
  },
  {
   "title": "Job Duration Improvement = SUM(task_duration) / job_duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 32 },
   "targets": [
    {
     "expr": "job:concurrency_factor_avg{test=\"$test_name\", scheme=\"$scheme\"}",
     "legendFormat": "Factor"
    }
   ]
  }
 ]
}