{
 "title": "Thread Pool Stats",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "pool_name", "label": "Pool Name", "query": { "query": "label_values(pool_name)" } },
   { "name": "test_name", "label": "Test Name", "query": { "query": "label_values(test)" } },
   { "name": "interval", "label": "Interval", "query": "3s" }
  ]
 },
 "panels": [
  {
   "title": "Pool Config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "first" ] } },
   "targets": [
    {
     "expr": "thread_pool:pool_config_core_size{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Config Core Size"
    },
    {
     "expr": "thread_pool:pool_config_max_size{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Pool Max Size"
    },
    {
     "expr": "thread_pool:queue_config_capacity{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Queue Capacity"
    }
   ]
  },
  {
   "title": "Pool Size",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
   "targets": [
    {
     "expr": "thread_pool:pool_size{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Pool Size"
    }
   ]
  },
  {
   "title": "Queue Size",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "thread_pool:queue_size{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Size"
    },
    {
     "expr": "thread_pool:queue_size_max_spike{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Size Max Spike"
    },
    {
     "expr": "thread_pool:queue_size_avg{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Queue Size Avg"
    },
    {
     "expr": "thread_pool:queue_size_moving_avg{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Queue Size Avg Moving"
    }
   ]
  },
  {
   "title": "Task Counters",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "thread_pool:tasks_count_total{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "thread_pool:tasks_completed_count_total{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Completed"
    }
   ]
  },
  {
   "title": "Active Tasks",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "thread_pool:tasks_active_count{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Active"
    },
    {
     "expr": "thread_pool:tasks_active_count_callback{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Active Callback"
    }
   ]
  },
  {
   "title": "Task Timing",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "thread_pool:task_queue_wait_duration_max_spike_ns{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Wait Max Spike"
    },
    {
     "expr": "thread_pool:task_duration_max_spike_ns{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Duration Max Spike"
    },
    {
     "expr": "thread_pool:task_duration_moving_avg_ns{pool_name=\"$pool_name\", test=\"$test_name\"}",
     "legendFormat": "Duration Moving Avg"
    }
   ]
  }
 ]
}