{
 "title": "JVM",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "test_name", "label": "Test Name", "query": { "query": "label_values(test)" } }
  ]
 },
 "panels": [
  {
   "title": "Heap Memory",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg(jvm:memory_bytes{test=\"$test_name\", type=\"total\"}) - avg(jvm:memory_bytes{test=\"$test_name\", type=\"free\"})",
     "legendFormat": "Heap Used"
    },
    {
     "expr": "jvm:memory_bytes{test=\"$test_name\", type=\"total\"}",
     "legendFormat": "Heap Total"
    }
   ]
  },
  {
   "title": "-Xmx",
   "type": "stat",
   "gridPos": { "h": 7, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "firstNotNull" ] } },
   "targets": [
    {
     "expr": "jvm:memory_bytes{test=\"$test_name\", type=\"max\"}",
     "legendFormat": "-Xmx"
    }
   ]
  },
  {
   "title": "CPU Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "jvm:cpu_load_percent{test=\"$test_name\"}",
     "legendFormat": "CPU Load"
    }
   ]
  },
  {
   "title": "Open File Descriptors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "jvm:open_file_descriptors_count{test=\"$test_name\"}",
     "legendFormat": "Descriptors"
    }
   ]
  }
 ]
}